from tkinter import *
root = Tk()
root.title("Getting Started with Widgets")
root.geometry("400x300")
label1 = Label(root, text="Enter two numbers to calculate their product", fg="red")
label1.pack()
label2 = Label(root, text="Enter first number:")
label2.pack()
entry1 = Entry(root)
entry1.pack()
label3 = Label(root, text="Enter second number:")
label3.pack()
entry2 = Entry(root)
entry2.pack()
label4 = Label(root, text="Result:")
label4.pack()
result_box = Text(root, height=2, width=20)
result_box.pack()
def product():
    n1 = int(entry1.get())
    n2 = int(entry2.get())
    res = n1*n2
    result_box.delete("1.0", END)
    result_box.insert(END, res)
button = Button(root, text="Calculate Product", command=product, bg="green", fg="white")
button.pack()
root.mainloop()